# Generated by Django 3.2.19 on 2024-01-02 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officials.agedivision')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.club')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('can_read_posts', models.BooleanField(default=True)),
                ('can_make_posts', models.BooleanField(default=True)),
                ('can_moderate_posts', models.BooleanField()),
                ('can_assign_all_games', models.BooleanField()),
                ('can_update_all_assignments', models.BooleanField()),
                ('can_create_games', models.BooleanField()),
                ('can_create_teams', models.BooleanField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=1000)),
                ('experience', models.CharField(help_text='E.g. Amount of years or seasons you have been an official', max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('organizations_permissions', models.ManyToManyField(blank=True, to='officials.OrganizationUserPermissions')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=5000)),
                ('starting', models.DateTimeField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('age_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officials.agedivision')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away', to='officials.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home', to='officials.team')),
                ('hosting_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officials.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Assignor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations_permissions', models.ManyToManyField(blank=True, help_text='Make sure that the user has assigning permissions.', to='officials.OrganizationUserPermissions')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Center Referee', 'Center Referee'), ('Assistant Referee 1', 'Assistant Referee 1'), ('Assistant Referee 2', 'Assistant Referee 2'), ('Fourth Official', 'Fourth Official'), ('Shadow Referee', 'Shadow Referee'), ('Assessor', 'Assessor'), ('Additional Official', 'Additional Official')], max_length=1000)),
                ('note', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.game')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
    ]
